LavenderTown_House1_Text_Cubone::
    .string "CUBONE: Kyarugoo!$"

LavenderTown_House1_Text_RocketsKilledCubonesMother::
    .string "Those horrible ROCKETS!\n"
    .string "They deserve no mercy!\p"
    .string "That poor CUBONE's mother…\p"
    .string "It was killed trying to escape from\n"
    .string "TEAM ROCKET.$"

LavenderTown_House1_Text_GhostOfPokemonTowerIsGone::
    .string "The ghost of POKéMON TOWER is\n"
    .string "gone!\p"
    .string "Someone must have soothed its\n"
    .string "restless spirit!$"   

LavenderTown_House1_Text_ResetEV::
    .string "I can help your lead POKéMON\n"
    .string "unlearn its bad habits if you like.$"

LavenderTown_House1_Text_ResetEVCompleted::
    .string "Your POKéMON's bad habits have\n"
    .string "been washed away!$"