VermilionCity_Text_GrimerMultipliesInSludge::
    .string "We're careful about pollution here.\p"
    .string "We've heard GRIMER multiplies in\n"
    .string "toxic sludge.$"

VermilionCity_Text_DidYouSeeSSAnneInHarbor::
    .string "Did you see the S.S. ANNE moored\n"
    .string "in the harbor?$"

VermilionCity_Text_SSAnneHasDepartedForYear::
    .string "So, the S.S. ANNE has departed?\p"
    .string "She'll be back in VERMILION about\n"
    .string "this time next year.$"

VermilionCity_Text_BuildingOnThisLand::
    .string "I'm watching POKéMON on this\n"
    .string "plot of land. I own it all.\p"
    .string "My POKéMON is playing with\n"
    .string "the other POKéMON.$"

VermilionCity_Text_Machop::
    .string "MACHOP: Guoh! Gogogoh!$"

VermilionCity_Text_MachopStompingLandFlat::
    .string "A MACHOP is playing here!$"

VermilionCity_Text_SSAnneVisitsOnceAYear::
    .string "The S.S. ANNE is a famous luxury\n"
    .string "cruise ship.\p"
    .string "It visits VERMILION once a year.$"

VermilionCity_Text_CitySign::
    .string "VERMILION CITY\n"
    .string "The Port of Exquisite Sunsets$"

VermilionCity_Text_SnorlaxBlockingRoute12::
    .string "NOTICE!\p"
    .string "ROUTE 12 may be blocked off by a\n"
    .string "sleeping POKéMON.\p"
    .string "Detour through ROCK TUNNEL to\n"
    .string "LAVENDER TOWN.\p"
    .string "VERMILION POLICE$"

VermilionCity_Text_PokemonFanClubSign::
    .string "POKéMON FAN CLUB\n"
    .string "All POKéMON fans welcome!$"

VermilionCity_Text_GymSign::
    .string "VERMILION CITY POKéMON GYM\n"
    .string "LEADER: LT. SURGE\l"
    .string "The Lightning American!$"

VermilionCity_Text_VermilionHarbor::
    .string "VERMILION HARBOR$"

VermilionCity_Text_WelcomeToTheSSAnne::
    .string "Welcome to the S.S. ANNE!$"

VermilionCity_Text_DoYouHaveATicket::
    .string "Welcome to the S.S. ANNE!\p"
    .string "Excuse me, do you have a ticket?$"

VermilionCity_Text_FlashedSSTicket::
    .string "{FONT_NORMAL}{PLAYER} flashed the S.S. TICKET!\p"
    .string "{FONT_MALE}Great!\n"
    .string "Welcome to the S.S. ANNE!$"

VermilionCity_Text_DontHaveNeededSSTicket::
    .string "{FONT_NORMAL}{PLAYER} doesn't have the needed\n"
    .string "S.S. TICKET.\p"
    .string "{FONT_MALE}Sorry!\p"
    .string "You need a ticket to get aboard.$"

VermilionCity_Text_TheShipSetSail::
    .string "The ship set sail.$"

VermilionCity_Text_BoardSeagallopTriPass::
    .string "Ah, you have a TRI-PASS.\p"
    .string "Would you like to board\n"
    .string "a SEAGALLOP ferry?$"

VermilionCity_Text_Seagallop7Departing::
    .string "Okay, everything's in order.\p"
    .string "SEAGALLOP HI-SPEED 7 will be\n"
    .string "departing immediately.$"

VermilionCity_Text_BoardSeagallopRainbowPass::
    .string "Ah, you have a RAINBOW PASS.\p"
    .string "Would you like to board\n"
    .string "a SEAGALLOP ferry?$"

VermilionCity_Text_OldSeaMapTakeYouToFarawayIsland::
    .string "What do you have there?\n"
    .string "A tattered old map, eh?\p"
    .string "Let's have a look.\n"
    .string "… … … … … …\p"
    .string "Where you're trying to go is an\n"
    .string "island that's far, far away.\p"
    .string "I can take you there, but it'll\n"
    .string "be a long trip.\p"
    .string "Let me know when you're ready\n"
    .string "to leave.$"

VermilionCity_Text_OhEonTicketTakeYouToSouthernIsland::
    .string "Oh! That's an EON TICKET!\n"
    .string "Now that is rare.\p"
    .string "It points to a tiny spit of an\n"
    .string "island south of HOENN.\p"
    .string "We'll be happy to take you to\n"
    .string "SOUTHERN ISLAND anytime.$"

VermilionCity_Text_OhMysticTicketTakeYouToNavelRock::
    .string "Oh! That's a MYSTICTICKET!\n"
    .string "Now that is rare.\p"
    .string "We'll be happy to take you to\n"
    .string "NAVEL ROCK anytime.$"

VermilionCity_Text_OhAuroraTicketTakeYouToBirthIsland::
    .string "Oh! That's an AURORATICKET!\n"
    .string "Now that is rare.\p"
    .string "We'll be happy to take you to\n"
    .string "BIRTH ISLAND anytime.$"

VermilionCity_Text_BoardSeagallopFerry::
    .string "Would you like to board\n"
    .string "a SEAGALLOP ferry?$"

VermilionCity_Text_Seagallop10Departing::
    .string "Okay, everything's in order for you\n"
    .string "to board a special ferry.\p"
    .string "SEAGALLOP HI-SPEED 10 will be\n"
    .string "departing immediately.$"

VermilionCity_Text_Seagallop12Departing::
    .string "Okay, everything's in order for you\n"
    .string "to board a special ferry.\p"
    .string "SEAGALLOP HI-SPEED 12 will be\n"
    .string "departing immediately.$"

VermilionCity_Text_Seagallop14Departing::
    .string "Okay, everything's in order for you\n"
    .string "to board a special ferry.\p"
    .string "SEAGALLOP HI-SPEED 14 will be\n"
    .string "departing immediately.$"

VermilionCity_Text_Seagallop13Departing::
    .string "Okay, everything's in order for you\n"
    .string "to board a special ferry to HOENN.\p"
    .string "SEAGALLOP HI-SPEED 13 will be\n"
    .string "departing immediately.$"

VermilionCity_Text_Route2AideHasPackageForYou::
    .string "Oh, hello, {PLAYER}!\n"
    .string "How are you doing?\p"
    .string "It's me, one of PROF. OAK's AIDES.\p"
    .string "Did you visit the MUSEUM in\n"
	.string "PEWTER CITY?\p"
    .string "The UNDERGROUND CHALLENGE exhibit\n"
	.string "was opened a few weeks ago.\p"
    .string "It's made to give visitors a taste\n"
    .string "of exploring a cave system.\p"
    .string "It is said that the prize at the\n"
    .string "end is very useful for exploring\l"
    .string "pitch-black caves.$"

VermilionCity_Text_JustCaughtASquirtle::
    .string "I just caught a SQUIRTLE that was\n"
    .string "always getting into misschief.\p"
    .string "I think it needs a good TRAINER\n"
    .string "to set it straight.$"

VermilionCity_Text_WantThisSquirtle::
    .string "You must be a good TRAINER!\p"
    .string "I just caught a SQUIRTLE that was\n"
    .string "always getting into misschief.\p"
    .string "Would you take good care of it?$"

VermilionCity_Text_Oh::
    .string "Oh… What am I to do now?$"

VermilionCity_Text_ObtainedSquirtleFromPolice::
    .string "{PLAYER} obtained a SQUIRTLE!$"

VermilionCity_Text_TreatHimRight::
    .string "OK! Please treat SQUIRTLE right!$"

VermilionCity_Text_HowIsSquirtle::
    .string "Hello! How is SQUIRTLE doing?$"