CinnabarIsland_House_Text_LittleGirl::
	.string "I'm watching a TV program made by\n"
	.string "the SCIENTISTS at CINNABAR LAB!\p"
	.string "It's about the formation\n"
	.string "of volcanoes!$"

CinnabarIsland_House_Text_OldLady::
	.string "My granddaughter found this by\n"
	.string "the shores a few days ago.\p"
	.string "Maybe you could use it.$"

CinnabarIsland_House_EventScript_FossilNoBagSpace::
	.string "You don't have space for this in\n"
    .string "your BAG.$"