

MtSilverGate_Text_NoPass::
	.string "I'm sorry, you\n"
	.string "cannot go past here.\p"
	.string "Come back when you have\n"
	.string "achieved greater feats.$"

MtSilverGate_Text_Pass::
	.string "I got word from the\n"
	.string "VIRIDIAN GYM LEADER.\p"
	.string "You can go through now.$"
MtSilverGate_Text_NewBarkNoPass::
	.string "Sorry buddy, past these routes\n"
	.string "lies the JOHTO region.\p"
	.string "There's nothing for you there.$"

MtSilverGate_Text_NewBarkPass::
	.string "I got word from the PROFESSOR.\p"
	.string "You are allowed access to\n"
	.string "ROUTE 26 and beyond.$"

MtSilverGate_Text_Mt_Silver::
	.string "MT. SILVER lies in this direction.\p"
	.string "The strongest TRAINERS come here\n"
	.string "to battle and train their POKéMON.$"

MtSilverGate_Text_Route_26::
	.string "ROUTE 26 lies in this direction.\p"
	.string "You're heading for JOHTO, right?$"

MtSilverGate_Text_Route_22::
	.string "ROUTE 22 lies in this direction.$"