TwoIsland_House_Text_TeachMonMoveForMushroom::
    .string "I'm the POKéMON MOVE MANIAC.\p"
    .string "I know every single move that\n"
    .string "POKéMON learn growing up.\p"
    .string "I'll teach a move that\n"
    .string "your POKéMON should know.\p"
    .string "Do you want me to teach a move\n"
    .string "to a POKéMON of yours?$"

TwoIsland_House_Text_TutorDone::
    .string "There! I taught it a new move.\p"
    .string "I hope it helps you on your\n"
    .string "adventure!$"
TwoIsland_House_Text_TutorWhichMon::
    .string "Which POKéMON needs tutoring?$"

TwoIsland_House_Text_TeachWhichMove::
    .string "Which move should I teach?$"

TwoIsland_House_Text_NoMoveICanTeachThatMon::
    .string "Sorry…\p"
    .string "It doesn't appear as if I have a\n"
    .string "move I can teach that POKéMON.$"
TwoIsland_House_Text_NeedMushroomOrTwoToLearnMove::
    .string "If your POKéMON need to learn a\n"
    .string "move, I'll do it for free.$"

TwoIsland_House_Text_CantTeachAnEgg::
    .string "Hunh? There isn't a single move\n"
    .string "that I can teach an EGG.$"

